/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/common/Autocomplete.vue')['default']
    BaseTable: typeof import('./src/components/table/BaseTable.vue')['default']
    Breadcrumb: typeof import('./src/components/common/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    Colspan: typeof import('./src/components/table/Colspan.vue')['default']
    Column: typeof import('./src/components/common/Column.vue')['default']
    ContentTop: typeof import('./src/components/common/ContentTop.vue')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PerPage: typeof import('./src/components/common/PerPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonTable: typeof import('./src/components/table/SkeletonTable.vue')['default']
    Tfoot: typeof import('./src/components/common/Tfoot.vue')['default']
    Thead: typeof import('./src/components/common/Thead.vue')['default']
  }
}
